name: Test Homebrew Formula
on:
  push:
    branches:
      - 'master'
jobs:
  Test:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-12]
    steps:
      - name: Tap icecube
        run: brew tap icecube/homebrew-icecube
      - name: Brew Install
        run: brew install --build-from-source erfa pal photospline sprng2 nuflux
      - name: Brew Test
        run: |
          eval "$(brew shellenv)"
          brew test photospline sprng2 nuflux erfa pal
